export enum SWRKeys {
  GET_ATTESTATION_BY_ID = "getAttestationByID",
  GET_SCHEMAS_LIST = "getSchemasList",
  GET_SCHEMAS_COUNT = "getSchemasCount",
  GET_SCHEMA_BY_ID = "getSchemaByID",
  GET_RELATED_ATTESTATION = "getRelatedAttestations",
  GET_ATTESTATION_LIST = "getAttestationList",
  GET_ATTESTATION_COUNT = "getAttestationCount",
  GET_RECENT_ATTESTATION_SCHEMA = "getRecentAttestationsSchema",
  GET_RECENT_ATTESTATION_PORTAL = "getRecentAttestationsPortal",
  GET_RECENT_ATTESTATION_GLOBAL = "getRecentAttestations",
  GET_MODULE_LIST = "getModuleList",
  GET_MODULE_COUNT = "getModuleCount",
  GET_MODULE_PORTAL_LIST = "getModulePortalList",
  SEARCH = "search",
  GET_PORTALS_BY_ISSUER = "getPortalsByIssuer",
  GET_PORTAL_BY_ID = "getPortalByID",
  GET_PORTAL_MODULE_LIST = "getPortalModuleList",
  GET_PORTAL_LIST = "getPortalList",
}
