/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        whiteDefault: "var(--white-default)",
        blackDefault: "var(--black-default)",
        blueDark: "var(--blue-dark)",
        greyDefault: "var(--grey-default)",
        greyDark: "var(--grey-dark)",
        greenDefault: "var(--green-default)",
        greenDark: "var(--green-dark)",
        jumbotron: "var(--jumbotron)",
        jumbotronLight: "var(--jumbotron-light)",
        jumbotronDark: "var(--jumbotron-dark)",
        tertiary: "var(--tertiary)",
        background: "var(--surface-primary)",
        borderCard: "var(--border)",
        skeleton: "var(--skeleton)",
        grey400: "var(--grey-400)",
        surface: {
          lime: "var(--surface-lime)",
          primary: "var(--surface-primary)",
          secondary: "var(--surface-secondary)",
          secondaryDark: "var(--surface-secondary-dark)",
          darkGrey: "var(--surface-dark-grey)",
          darkGreyDark: "var(--surface-dark-grey-dark)",
          lightBlack: "var(--surface-light-black)",
          attestationData: "var(--surface-attestation-data)",
          attestationDataDark: "var(--surface-attestation-data-dark)",
          magenta20: "var(--surface-magenta-20)",
          magenta20Dark: "var(--surface-magenta-20-dark)",
        },
        text: {
          input: "var(--text-input)",
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          secondaryDark: "var(--text-secondary-dark)",
          tertiary: "var(--text-tertiary)",
          quaternary: "var(--text-quaternary)",
          darkGrey: "var(--text-dark-grey)",
          darkBlue: "var(--text-dark-blue)",
        },
        border: {
          card: "var(--border-card)",
          cardDark: "var(--border-card-dark)",
          cardHover: "var(--border-card-hover)",
          cardHoverDark: "var(--border-card-dark-hover)",
          table: "var(--border-table)",
          tableDark: "var(--border-table-dark)",
          input: "var(--border-input)",
          inputFocus: "var(--border-input-focus)",
        },
        page: {
          attestation: "var(--indicator-blue)",
          attestationDark: "var(--indicator-blue-dark)",
          schema: "var(--indicator-magenta)",
          schemaDark: "var(--indicator-magenta-dark)",
          portal: "var(--indicator-green)",
          portalDark: "var(--indicator-green-dark)",
          module: "var(--indicator-orange)",
          moduleDark: "var(--indicator-orange-dark)",
        },
        hover: {
          lime20: "var(--hover-lime20)",
        },
        button: {
          primary: {
            background: "var(--button-primary-background)",
            text: "var(--button-primary-text)",
            hover: "var(--button-primary-hover)",
            hoverDark: "var(--button-primary-dark-hover)",
          },
          primaryWhite: {
            background: "var(--button-primary-white-background)",
            text: "var(--button-primary-white-text)",
            hover: "var(--button-primary-white-hover)",
            hoverDark: "var(--button-primary-white-dark-hover)",
          },
          primaryBlack: {
            background: "var(--button-primary-black-background)",
            text: "var(--button-primary-black-text)",
            hover: "var(--button-primary-black-hover)",
          },
          secondary: {
            background: "var(--button-secondary-background)",
            text: "var(--button-secondary-text)",
            hover: "var(--button-secondary-hover)",
            border: "var(--button-secondary-border)",
            borderHover: "var(--button-secondary-border-hover)",
          },
          outlined: {
            text: "var(--button-outlined-text)",
            border: "var(--button-outlined-border)",
            borderDark: "var(--button-outlined-border-dark)",
            borderHover: "var(--button-secondary-border-hover)",
            borderDarkHover: "var(--button-secondary-border-dark-hover)",
          },
        },
      },
      transitionProperty: {
        height: "height",
        spacing: "margin, padding, gap",
      },
      fontFamily: {
        IBMPlexMono: ["IBM Plex Mono", "monospace"],
        inter: ["Inter", "sans-serif"],
      },
      boxShadow: {
        column: "3px 0px 10px 0px rgba(197,197,197,0.19)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
