name: Explorer production

on:
  workflow_dispatch:

permissions: {} # lock everything by default (least-privilege)

jobs:
  deploy-explorer-prod:
    if: >-
      github.ref == 'refs/heads/main' && (
        github.actor == 'alainncls' || github.actor == 'satyajeetkolhapure' || github.actor == 'orbmis' ||
        github.actor == 'arthur-remy' || github.actor == 'ars9' || github.actor == 'Solniechniy'
      )

    runs-on: ubuntu-latest
    environment: explorer-production
    permissions:
      contents: read

    defaults:
      run:
        working-directory: explorer

    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm run build:netlify
        env:
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}
          VITE_INFURA_API_KEY: ${{ secrets.VITE_INFURA_API_KEY }}
          VITE_THE_GRAPH_API_KEY: ${{ secrets.VITE_THE_GRAPH_API_KEY }}

      - name: Deploy explorer to Netlify
        run: pnpm exec netlify deploy --dir=dist --site="$NETLIFY_SITE_ID" --prod --no-build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Add explorer deployment summary
        run: |
          echo "## Explorer production deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
