name: Deploy preview explorer

on:
  pull_request:
    branches:
      - dev
    paths:
      - explorer/**

jobs:
  deploy-explorer-preview:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: explorer

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: check-changes
        run: |
          if [ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^explorer/')" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Install Pnpm
        if: steps.check-changes.outputs.changed == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        if: steps.check-changes.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Get pnpm store directory
        if: steps.check-changes.outputs.changed == 'true'
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        if: steps.check-changes.outputs.changed == 'true'
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: steps.check-changes.outputs.changed == 'true'
        run: pnpm install --frozen-lockfile

      - name: Build
        if: steps.check-changes.outputs.changed == 'true'
        run: pnpm run build:netlify
        env:
          VITE_WALLETCONNECT_PROJECT_ID: ${{ secrets.VITE_WALLETCONNECT_PROJECT_ID }}
          VITE_INFURA_API_KEY: ${{ secrets.VITE_INFURA_API_KEY }}

      - name: Deploy to Netlify
        if: steps.check-changes.outputs.changed == 'true'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./explorer/dist"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
        timeout-minutes: 1

      - name: Add explorer deployment summary
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          echo "## Explorer staging deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: Add explorer deployment summary
        if: steps.check-changes.outputs.changed == 'false'
        run: |
          echo "## Explorer staging deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ No change detected in the explorer" >> $GITHUB_STEP_SUMMARY
