name: Explorer

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
  push:
    branches:
      - main
      - dev
      - release/*

permissions: {} # lock everything by default (least-privilege)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-explorer:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: explorer

    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm run build

      - name: Add build summary
        run: |
          echo "## Explorer build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
