name: Explorer

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
  push:
    branches:
      - main
      - dev
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-explorer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: explorer

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm run build

      - name: Add build summary
        run: |
          echo "## Explorer build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
