name: Lint

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
  push:
    branches:
      - main
      - dev
      - release/*

permissions: {} # lock everything by default (least-privilege)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Check code linting
        run: pnpm -r run lint

      - name: Run Prettier
        run: pnpm run prettier:check

      - name: Add lint summary
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
