name: New version releaser

on:
  workflow_dispatch:

permissions: {} # lock everything by default (least-privilege)

jobs:
  release:
    if:
      github.actor == 'alainncls' || github.actor  == 'satyajeetkolhapure' || github.actor  == 'orbmis' ||
      github.actor  == 'arthur-remy'

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PROD_RELEASER_GH_TOKEN }}

      - name: "Run release script"
        run: ./release.sh
