name: New version releaser

on:
  workflow_dispatch:

permissions: {} # lock everything by default (least-privilege)

concurrency:
  group: production-release
  cancel-in-progress: false

jobs:
  release:
    if: >-
      github.ref == 'refs/heads/main' && (
        github.actor == 'alainncls' ||
        github.actor == 'satyajeetkolhapure' ||
        github.actor == 'orbmis' ||
        github.actor == 'arthur-remy'
      )

    runs-on: ubuntu-latest
    environment: production-release
    permissions:
      contents: read

    steps:
      - name: "Check out the repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.PROD_RELEASER_GH_TOKEN }}

      - name: "Run release script"
        run: ./release.sh
