name: SDK

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
  push:
    branches:
      - main
      - dev
      - release/*

permissions: {} # lock everything by default (least-privilege)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: sdk

    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run the unit tests
        run: pnpm run test:unit:coverage

      - name: Move the report at the root of the 'sdk' folder
        run: mv coverage/lcov.info .

      - name: Upload coverage report to Codecov
        if: env.CODECOV_TOKEN != ''
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: ./sdk/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Check test coverage
        uses: terencetcf/github-actions-lcov-minimum-coverage-checker@537e486d32b4763f3be8fbe81a79c3421071b190 # v1.4.1
        with:
          coverage-file: sdk/lcov.info
          minimum-coverage: 50

      - name: Add coverage summary if upload
        if: env.CODECOV_TOKEN != ''
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          echo "## Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to Codecov" >> $GITHUB_STEP_SUMMARY

      - name: Add coverage summary if no upload
        if: env.CODECOV_TOKEN == ''
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          echo "## Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Coverage not uploaded to Codecov" >> $GITHUB_STEP_SUMMARY

  integration-test-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: sdk

    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run the integration tests
        run: pnpm run test:integration:ci

      - name: Integration tests summary
        run: |
          echo "## Integration tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ All passed" >> $GITHUB_STEP_SUMMARY
