name: Subgraph

on:
  pull_request:
    branches:
      - main
      - dev
      - release/*
  push:
    branches:
      - main
      - dev
      - release/*

permissions: {} # lock everything by default (least-privilege)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-subgraph:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    defaults:
      run:
        working-directory: subgraph

    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build the subgraph
        run: pnpm run build:linea-sepolia

      - name: Run the unit tests
        run: pnpm run test

      - name: Add test summary
        run: |
          echo "## Unit tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
